# This is a basic workflow to help you get started with Actions
name: deploy-rc

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "next" ]
  pull_request:
    branches: [ "next" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3
      
      - name: install dependencies
        run: npm ci
        
      - name: build
        run: npm run build-storybook
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: storybook_doc
          path: ./storybook-static
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github Page
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact_name: storybook_doc
    
